# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: tenants
#   namespace: flux-system
# spec:
#   interval: 1m
#   chart: 
#     spec:
#       chart: tenants
#       version: '1.0.0'
#       sourceRef:
#         kind: HelmRepository
#         name: chartmuseum-csdn
#   targetNamespace: csdn-demo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: registry.hhstechgroup.com/hhs-cloud/content-service:dev-*
  name: content-ui
  namespace: flux-system
spec:
  interval: 1m
  values:
    image:
      name: dev-43
    replicaCount: 1
  chart: 
    spec:
      chart: content-ui
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-csdn
  targetNamespace: csdn-demo
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: usermanagement-ui
#   namespace: flux-system
# spec:
#   interval: 1m
#   chart: 
#     spec:
#       chart: usermanagement-ui
#       version: '1.0.0'
#       sourceRef:
#         kind: HelmRepository
#         name: chartmuseum-csdn
#   targetNamespace: csdn-demo
  
