apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongo
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: mongo
      version: '2.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-csdn
  targetNamespace: csdn-demo
