apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: elasticsearch
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-csdn
  targetNamespace: csdn-demo